apiVersion: v1
kind: Pod
metadata:
  name: pod-cmd-args
spec:
  containers:
  - name: command-demo-ctr
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
