apiVersion: v1
kind: Pod
metadata:
  name: emptydir-init
spec:
  restartPolicy: Never
  containers:
  - name: nginx-ctr
    image: nginx
    volumeMounts:
    - name: emptydir-vol
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: debian-ctr
    image: debian
    volumeMounts:
    - name: emptydir-vol
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello > /pod-data/index.html"]
  volumes:
  - name: emptydir-vol
    emptyDir: {}
