apiVersion: v1
kind: Pod
metadata:
  name: hostpath-basic
spec:
  containers:
  - name: nginx-ctr
    image: nginx
    volumeMounts:
    - name: hostpath-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/sapan2211/LFS258/volumes/html
